### PR TITLE
add to the batch_processing function

### PR DESCRIPTION
**Pull request by j-friedrich**
- Add fit with  fiphasic exponential decay (bleaching)  x  increasing saturating exponential (brightening) [issues #1 and #2]
- Remove unnecessary duplicated function `batch_processing_new` [issue #1]
- Remove unnecessary files from repo [issue #6]

### CODE REVIEW

**Comment by alexpiet** [comment]
@hagikent Can you review this PR for accurate preprocessing?
@Ahad-Allen Can you review this PR for smooth running on our pipeline?

I can't speak to either of those issues. So once you two sign off, lets approve it and merge it in.

**Review by Ahad-Allen — COMMENTED** [review]
I'm not an expert on running these pipelines automatically, but all seems well to me at initial glance! I just added one bit of feedback on perhaps wanting to support both hd5 and zarr nwb files due to some dandi related issues with zarr files atm

**Comment by Ahad-Allen** [comment]
I tested this with a copy of our pipeline and it generated NWB files with the expected timestamps and seems to work appropriately. The dataframes generated and nwb files generated will now have timestamps for each pre-processing type, rather than one "preprocessed" set of multiple timestamps.

**Review by alexpiet — APPROVED** [review]
Approving because it improves the double time stamp issue. I cannot evaluate the scientific validity of the preprocessing, so @hagikent should evaluate after SFN

**Pull request merged**
